config/routes.rb
SpdxDashboard::Application.routes.draw do
  resources :spdx_docs do
    get :compare, on: :member
    get :files, on: :member

    resources :comments
    resources :package_files, path: "files"
  end

  resources :packages do
    get "find", on: :collection
    resources :package_files, path: "files"
    resources :comments
  end

  resources :package_files

  resources :licenses

  root to: "spdx_docs#index"
end

app/models/package_file.rb
class PackageFile < ActiveRecord::Base
  attr_accessible :artifact_homepage, 
                  :artifact_name, 
                  :artifact_uri, 
                  :checksum_id, 
                  :copyright_text, 
                  :copyright_text, 
                  :license_concluded_id, 
                  :license_declared_id, 
                  :name, 
                  :package_id, 
                  :type

  belongs_to :package
  belongs_to :license_declared, class_name: "License"
  belongs_to :license_concluded, class_name: "License"
  has_many :optional_fields, as: :owner
  has_many :licensings
  has_many :licenses, through: :licensings
  has_many :comments, as: :owner

  after_create :determine_relative_path

  def name_without_path
    return name unless name.match /.tar\/(.+)/
    $1
  end

  def name_without_package
    parts = name.split("/")
    parts.delete_if { |part| part.include?(self.package.simple_name) || part == "." }
    parts.join("/")
  end

  def spdx_doc
    package.spdx_doc
  end

  private
  def determine_relative_path
    self.relative_path = self.name_without_package
    save
  end
end

# == Schema Information
#
# Table name: package_files
#
#  id                   :integer          not null, primary key
#  package_id           :integer
#  name                 :string(255)
#  file_type            :string(255)
#  copyright_text       :string(255)
#  artifact_name        :string(255)
#  artifact_homepage    :string(255)
#  artifact_uri         :string(255)
#  license_concluded_id :string(255)
#  license_declared_id  :string(255)
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  checksum             :string(255)
#  checksum_algorithm   :string(255)
#  relative_path        :string(255)
#

app/controllers/package_files_controller.rb
class PackageFilesController < ApplicationController
  def show
    @spdx_doc = SpdxDoc.find(params[:spdx_doc_id])
    @file = @spdx_doc.package.files.find(params[:id])
  end
end

app/helpers/package_files_helper.rb
module PackageFilesHelper
end

app/views/package_files/show.html.erb
<% @page_title = "#{@spdx_doc.name} > Files > #{@file.name_without_path}" %>

<h3>
  <%= link_to "SPDX Docs", root_path %>
  >
  <%= link_to @spdx_doc.name, @spdx_doc %>
  >
  <%= link_to "Files", files_spdx_doc_path(@spdx_doc) %>
  >
  <%= @file.name_without_path %>
</h3>

<hr>

<div class="row-fluid">
  <h4>File Info</h4>
  <div class="span10">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td class="tr-title">File type</td>
          <td><%= @file.file_type %></td>
        </tr>
        <tr>
          <td class="tr-title">Checksum (<%= @file.checksum_algorithm %>)</td>
          <td><%= @file.checksum %></td>
        </tr>
        <tr>
          <td class="tr-title">License concluded</td>
          <td>n/a</td>
        <tr>
          <td class="tr-title">License declared</td>
          <td>n/a</td>
        </tr>
        <tr>
          <td class="tr-title">Comment</td>
          <td>n/a</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>