config/routes.rb
SpdxDashboard::Application.routes.draw do
  resources :spdx_docs do
    get :compare, on: :member
    get :files, on: :member

    resources :comments
    resources :package_files, path: "files"
  end

  resources :packages do
    get "find", on: :collection
    resources :package_files, path: "files"
    resources :comments
  end

  resources :package_files

  resources :licenses

  root to: "spdx_docs#index"
end

app/models/spdx_doc.rb
class SpdxDoc < ActiveRecord::Base
  attr_accessible :comment_id, :spec_version, :upload

  has_one :package
  has_many :optional_fields, as: :owner
  has_many :comments, as: :owner
  has_many :license_refs
  has_many :licenses, through: :license_refs
  has_attached_file :upload

  validates_attachment :upload, presence: true,
  content_type: { content_type: "application/octet-stream" }

  # Friendly name methods
  def name
    upload_file_name
  end

  def version
    return "n/a" unless spec_version.present?
    spec_version
  end

  def ensure_encoding(line)
    require 'iconv' unless String.method_defined?(:encode)
    if String.method_defined?(:encode)
      line.encode!('UTF-8', 'UTF-8', :invalid => :replace)
    else
      ic = Iconv.new('UTF-8', 'UTF-8//IGNORE')
      line = ic.iconv(line)
    end
    line
  end

  # Parsing and relationship methods
  def parse_tag!
    tag_file = File.open(upload.path)
    lines = File.readlines(upload.path)

    ## PARSE DOCUMENT INFO
    tag_file.each_line do |line|
      ensure_encoding(line)
      if line.match /^SPDXVersion: (.+)/
        self.spec_version = $1.delete("\r")
      end

      if line.match /^DataLicense: (.+)/
        self.data_license = $1.delete("\r")
      end

      if line.match /^DocumentComment: <text>(.+)<\/text>/
        self.document_comment = $1.delete("\r")
      end

      if line.match /^CreatorComment: <text>(.+)<\/text>/
        self.creator_comment = $1.delete("\r")
      end

      if line.match /^Created: (.+)/
        self.generated_at = $1.delete("\r").to_datetime
      end
    end
    self.save

    ## PARSE PACKAGE INFO
    package = self.build_package

    package_lines = lines.select { |line| ensure_encoding(line)[/^Package/] }
    package_lines.each do |line|
      line = ensure_encoding(line)
      if line.match /^PackageName: (.+)/
        package.name = $1.delete("\r")
      end

      if line.match /^PackageVersion: (.+)/
        package.version = $1.delete("\r")
      end

      if line.match /^PackageDownloadLocation: (.+)/
        package.download_location = $1.delete("\r")
      end

      if line.match /^PackageSummary: (.+)/
        package.summary = $1.delete("\r")
      end

      if line.match /^PackageFileName: (.+)/
        package.filename = $1.delete("\r")
      end

      if line.match /^PackageSupplier: (.+)/
        package.supplier = $1.delete("\r")
      end

      if line.match /^PackageOriginator: (.+)/
        package.originator = $1.delete("\r")
      end

      if line.match /^PackageChecksum:\W(.+):\W(.+)/
        package.checksum_algorithm = $1.delete("\r")
        package.checksum = $2.delete("\r")
      end

      if line.match /^PackageDescription: <text>(.+)<\/text>/
        package.description = $1.delete("\r")
      end

      if line.match /^PackageCopyrightText: <text>(.+)<\/text>/
        package.copyright = $1.delete("\r")
      end
    end
    package.save

    self.reload

    ## PARSE LICENSE REFS
    lines.each_with_index do |line, index|
      line = ensure_encoding(line)
      if line.match /^LicenseID: (.+)/
        ref_name = $1.delete("\r")

        if lines[index + 1].match /^ExtractedText: <text>(.+)<\/text>/
          license_content = $1.delete("\r")
        end

        if lines[index + 2].match /^LicenseName: (.+)/
          license_name = $1.delete("\r")
        end

        license = License.create_or_find_for({ name: license_name, content: license_content })
        license.content = license_content
        license.save

        ref             = self.license_refs.build
        ref.license_id  = license.id
        ref.ref_name    = ref_name
        ref.save
      end
    end

    self.reload

    ## PARSE FILE INFO
    lines.each_with_index do |line, index|
      line = ensure_encoding(line)
      if line.match /^FileName: (.+)/
        package_file = package.files.new(name: $1.delete("\r"))

        if lines[index + 1].match /^FileType: (.+)/
          package_file.file_type = $1.delete("\r")
        end

        if lines[index + 2].match /^FileChecksum: (.+): (.+)/
          package_file.checksum_algorithm = $1
          package_file.checksum = $2.delete("\r")
        end

        if lines[index + 3].match /^LicenseConcluded: (.+)/
          license_or_ref = $1.delete("\r")

          if license_or_ref.match /^LicenseRef/
            license_ref = license_refs.find_by_ref_name(license_or_ref)
            license = license_ref.license
          else
            license = License.create_or_find_for(name: license_or_ref)
          end

          package_file.license_concluded_id = license.id
        end

        if lines[index + 4].match /^LicenseInfoInFile: (.+)/
          license_or_ref = $1.delete("\r")

          if license_or_ref.match /LicenseRef/
            license_ref = self.license_refs.find_by_ref_name(license_or_ref)
            license = license_ref.license
          else
            license = License.create_or_find_for(name: license_or_ref)
          end

          package_file.license_declared_id = license.id
        end

        if lines[index + 5].match /^FileCopyrightText: <text>(.+)<\/text>/
          package_file.copyright_text = $1.delete("\r");
        end

        package_file.save
      end
    end

    save
  end
end

# == Schema Information
#
# Table name: spdx_docs
#
#  id                  :integer          not null, primary key
#  spec_version        :string(255)
#  data_license        :string(255)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  upload_file_name    :string(255)
#  upload_content_type :string(255)
#  upload_file_size    :integer
#  upload_updated_at   :datetime
#  document_comment    :text
#  creator_comment     :text
#  generated_at        :datetime
#

app/controllers/spdx_docs_controller.rb
class SpdxDocsController < ApplicationController
  def index
    @spdx_docs = SpdxDoc.scoped.order('created_at DESC')
    @spdx_doc = SpdxDoc.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @spdx_docs }
    end
  end

  def show
    @spdx_doc = SpdxDoc.find(params[:id])
    @spdx_comment = @spdx_doc.comments.new
    @package = @spdx_doc.package
    @package_comment = @package.comments.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @spdx_doc }
    end
  end

  def new
    @spdx_doc = SpdxDoc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @spdx_doc }
    end
  end

  def edit
    @spdx_doc = SpdxDoc.find(params[:id])
  end

  def create
    @spdx_doc = SpdxDoc.new(params[:spdx_doc])

    respond_to do |format|
      if @spdx_doc.save
        @spdx_doc.parse_tag!
        format.html { redirect_to @spdx_doc, notice: 'Spdx doc was successfully created.' }
        format.json { render json: @spdx_doc, status: :created, location: @spdx_doc }
      else
        format.html { render action: "new" }
        format.json { render json: @spdx_doc.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @spdx_doc = SpdxDoc.find(params[:id])

    respond_to do |format|
      if @spdx_doc.update_attributes(params[:spdx_doc])
        format.html { redirect_to @spdx_doc, notice: 'Spdx doc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @spdx_doc.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @spdx_doc = SpdxDoc.find(params[:id])
    @spdx_doc.destroy

    respond_to do |format|
      format.html { redirect_to spdx_docs_url }
      format.json { head :no_content }
    end
  end

  ## NON RESTful routes
  ############################################################

  def files
    @spdx_doc = SpdxDoc.find(params[:id])
    @package = @spdx_doc.package
    @files = @package.files

    respond_to do |format|
      format.html
      format.json { render json: @files }
    end
  end

  def compare
    @doc1 = SpdxDoc.find(params[:id])
    @package1 = @doc1.package
    @files1 = @package1.files

    @doc2 = SpdxDoc.find(params[:to])
    @package2 = @doc2.package
    @files2 = @package2.files

    added = []
    deleted = []
    changed = []
    unchanged = []

    @files1.each do |file|
      same_file = @files2.find_by_relative_path(file.relative_path)
      if same_file.present?
        if file.checksum == same_file.checksum
          unchanged << file
        else
          changed << file
        end
      else
        deleted << file
      end
    end

    @files2.each do |file|
      unless @files1.find_by_relative_path(file.relative_path).present?
        added << file
      end
    end

    @file_diffs = {
      added: added,
      deleted: deleted,
      changed: changed,
      unchanged: unchanged
    }
  end
end

app/helpers/spdx_docs_helper.rb
module SpdxDocsHelper
end

app/views/spdx_docs/_compare_document_table.html.erb
<table class="table table-bordered">
  <thead>
    <th></th>
    <th><%= @doc1.name %> (1)</th>
    <th><%= @doc2.name %> (2)</th>
  </thead>
  <tbody>
    <tr>
      <td class="tr-title">Document creator</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="tr-title">Created date</td>
      <td><%= friendly_date(@doc1.created_at) %></td>
      <td><%= friendly_date(@doc2.created_at) %></td>
    </tr>
    <tr>
      <td class="tr-title">Document comment</td>
      <td><%= @doc1.document_comment %></td>
      <td><%= @doc2.document_comment %></td>
    </tr>
    <tr>
      <td class="tr-title">Package name</td>
      <td><%= @package1.name %></td>
      <td><%= @package2.name %></td>
    </tr>
    <tr>
      <td class="tr-title">Package version</td>
      <td><%= @package1.version %></td>
      <td><%= @package2.version %></td>
    </tr>
    <tr>
      <td class="tr-title">Package Licenses Concluded</td>
      <td></td>
      <td></td>
    </tr>
    <tr>
      <td class="tr-title">Package Copyright</td>
      <td><%= @package1.copyright %></td>
      <td><%= @package2.copyright %></td>
    </tr>
    <tr>
      <td class="tr-title">Package file count</td>
      <td><%= @files1.count %></td>
      <td><%= @files2.count %></td>
    </tr>
    <tr>
      <td class="tr-title">Package License Information</td>
      <td>
        <ul id="licenses" class="unstyled">
          <% @doc1.licenses.order(:name).each do |license| %>
            <li><%= link_to license.name, license %></li>
          <% end %>
        </ul>
      </td>
      <td>
        <ul id="licenses" class="unstyled">
          <% @doc2.licenses.order(:name).each do |license| %>
            <li><%= link_to license.name, license %></li>
          <% end %>
        </ul>
      </td>
    </tr>
  </tbody>
</table>

app/views/spdx_docs/_compare_files_table.html.erb
  <table class="table table-bordered">
    <thead>
      <th></th>
      <th><%= @doc1.name %> (1)</th>
      <th><%= @doc2.name %> (2)</th>
    </thead>
    <tbody>

      <% @file_diffs[:added].each do |file| %>
        <tr class="success">
          <td class="tr-title"><%= file.name_without_path %></td>
          <td></td>
          <td></td>
        </tr>
      <% end %>

      <% @file_diffs[:deleted].each do |file| %>
        <tr class="error">
          <td class="tr-title"><%= file.name_without_path %></td>
          <td></td>
          <td></td>
        </tr>
      <% end %>

      <% @file_diffs[:changed].each do |file| %>
        <tr class="alert">
          <td><%= file.name_without_path %></td>
          <td></td>
          <td><%= file.license_concluded.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/spdx_docs/_doc_select_box.html.erb
<div id="doc_select" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="docSelectModal" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="docSelectModal">Choose document for comparison</h3>
  </div>

  <div class="modal-body">
    <table class="table-hover">
      <% @spdx_docs.each do |spdx_doc| %>
        <tr>
          <td data-id="<%= spdx_doc.id %>">
            <button class="btn btn-link">
              <%= spdx_doc.name %>
            </button>
          </td>
        </tr>
      <% end %>
    </table>
  </div>

  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
  </div>
</div>

app/views/spdx_docs/_form.html.erb
<%= form_for(@spdx_doc) do |f| %>
  <% if @spdx_doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spdx_doc.errors.count, "error") %> prohibited this spdx_doc from being saved:</h2>

      <ul>
      <% @spdx_doc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :spec_version %><br />
    <%= f.text_field :spec_version %>
  </div>
  <div class="field">
    <%= f.label :comment_id %><br />
    <%= f.text_field :comment_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spdx_docs/_spdx_table.html.erb
<table class="table table-bordered table-spdx">

  <% spdx_docs.each do |spdx_doc| %>
    <tr>
      <td class="td-timestamp">
        <p class="greybox">
          <i class="icon-time"></i>
          <%= friendly_date(spdx_doc.created_at) %>
        </p>
      </td>

      <td class="td-main">
        <%= link_to spdx_doc.name, spdx_doc %>
      </td>

      <td class="td-controls greybox">
        <div class="btn-toolbar">
          <div class="btn-group">
            <%= link_to(spdx_doc.upload.url, class: "btn") do %>
              <i class="icon-download-alt"></i>
              download
            <% end %>

            <a href="#doc_select" role="button" class="btn" data-toggle="modal" data-id="<%= spdx_doc.id %>">
              <i class="icon-exchange"></i>
              compare
            </a>
          </div>
        </div>
      </td>
    </tr>
  <% end %>
</table>

app/views/spdx_docs/_upload_form.html.erb
<div id="upload_form">
  <%= form_for spdx_doc, html: { class: "form-inline", multipart: true } do |f| %>
    <%= f.file_field :upload %>
  <% end %>
  <button class="btn-upload btn btn-primary">
    <i class="icon-cloud-upload"></i>
    Upload
  </button>
  <span class="error" style="display: none;">
    <i class="icon-exclamation-sign"></i>
    File must be .tag
  <span>
</div>

app/views/spdx_docs/compare.html.erb
<% @page_title = "Compare" %>
<h2>Comparing <%= link_to @doc1.name, @doc1 %> (1) to <%= link_to @doc2.name, @doc2 %> (2)</h4>
<div id="compare" class="span12">
  <h4>Document + Package Changes</h4>
  <%= render partial: "compare_document_table" %>


  <h4>
    File changes

    <span class="comparisons">
      <span class="added">
        <i class="icon-plus-sign"></i>
        <%= @file_diffs[:added].count %>
        added
      </span>

      <span class="deleted">
        <i class="icon-minus-sign"></i>
        <%= @file_diffs[:deleted].count %>
        deleted
      </span>

      <span class="changed">
        <i class="icon-edit"></i>
        <%= @file_diffs[:changed].count %>
        changed
      </span>

      <span class="unchanged">
        <i class="icon-ok-sign"></i>
        <%= @file_diffs[:unchanged].count %>
        unchanged
      </span>
    </span>
  </h4>

  <% unless @file_diffs[:added].empty? && @file_diffs[:deleted].empty? && @file_diffs[:changed].empty? %>
    <%= render partial: "compare_files_table" %>
  <% else %>
    <div class="alert alert-info">
      No file changes found.
    </div>
  <% end %>
</div>

app/views/spdx_docs/edit.html.erb
<h1>Editing spdx_doc</h1>

<%= render 'form' %>

<%= link_to 'Show', @spdx_doc %> |
<%= link_to 'Back', spdx_docs_path %>

app/views/spdx_docs/files.html.erb
<% @page_title = "#{@spdx_doc.name} > Files" %>

<h1><%= link_to "SPDX Docs", root_path %> > <%= link_to @spdx_doc.name , @spdx_doc %> > Files </h1>

<hr>

<div class="row-fluid">
  <h2><%= @files.count %> files</h2>

  <div class="span11">
    <table class="table table-bordered table-striped">
      <thead>
        <th>File name</th>
        <th>File type</th>
        <th></th>
      </thead>

      <tbody>
        <% @files.each do |file| %>
          <tr>
            <td><%= file.name_without_path %></td>
            <td><%= file.file_type %>
            <td><%= link_to "View", [@spdx_doc, file] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/spdx_docs/index.html.erb
<% @page_title = "Docs" %>
<h1><%= @page_title %> (<%= @spdx_docs.count %>)</h1>
<%= render partial: "spdx_table", locals: {spdx_docs: @spdx_docs} %>

<%= render partial: "doc_select_box" %>

app/views/spdx_docs/new.html.erb
<h1>New spdx_doc</h1>

<%= render 'form' %>

<%= link_to 'Back', spdx_docs_path %>

app/views/spdx_docs/show.html.erb
<% @page_title = @spdx_doc.name %>

<h1><%= link_to "Docs", root_path %> > <%= @page_title %></h1>

<hr>

<div class="row-fluid">
  <h3>Document Info</h3>

  <div class="span6">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td class="tr-title">File name</td>
          <td><%= @spdx_doc.name %></td>
        </tr>
        <tr>
          <td class="tr-title">Date uploaded</td>
          <td><%= friendly_date(@spdx_doc.created_at) %></td>
        </tr>
        <tr>
          <td class="tr-title">Date generated</td>
          <td><%= friendly_date(@spdx_doc.generated_at) %></td>
        </tr>
        <tr>
          <td class="tr-title">SPDX version</td>
          <td><%= @spdx_doc.version %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="span5">
    <ul class="nav nav-tabs nav-stacked">
      <li>
        <%= link_to @spdx_doc.upload.url do %>
          <i class="icon-download"></i>
          Download
        <% end %>
      </li>
      <li>
        <%= link_to spdx_doc_comments_path(@spdx_doc) do %>
          <i class="icon-comment"></i>
          Comments (<%= @spdx_doc.comments.count %>)
        <% end %>
      </li>
    </ul>
    <%= form_for [@spdx_doc, @spdx_comment] do |f| %>
      <div class="input-append">
        <%= f.text_field :content, placeholder: "Comment on this document", class: "span10", disabled: true %>
        <%= f.submit "Add comment", class: "btn btn-primary", disabled: true %>
      </div>
    <% end %>
  </div>
</div>

<div class="row-fluid">
  <h3>Package Info</h3>
  <div class="span6">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <td class="tr-title">Package name</td>
          <td><%= @package.name %></td>
        </tr>
        <tr>
          <td class="tr-title">File name</td>
          <td><%= @package.filename %></td>
        </tr>
        <tr>
          <td class="tr-title">Package files</td>
          <td><%= link_to "#{@package.files.count} total (click to view)", 
          files_spdx_doc_path(@spdx_doc) %></td>
        </tr>
        <tr>
          <td class="tr-title">Package version</td>
          <td><%= @package.version %></td>
        </tr>
        <tr>
          <td class="tr-title">Originator</td>
          <td><%= @package.originator %></td>
        </tr>
        <tr>
          <Td class="tr-title">Supplier</td>
          <td><%= @package.supplier %></td>
        </tr>
        <tr>
          <td class="tr-title">Download location</td>
          <td><%= @package.download_location %></td>
        </tr>
        <tr>
          <td class="tr-title">Description</td>
          <td><%= @package.description %></td>
        </tr>
        <tr>
          <td class="tr-title">Copyright</td>
          <td><%= @package.copyright %></td>
        </tr>
        <tr>
          <td class="tr-title">Licenses</td>
          <td>
            <ul id="licenses" class="unstyled">
              <% @spdx_doc.licenses.order(:name).each do |license| %>
                <li><%= link_to license.name, license %></li>
              <% end %>
            </ul>
          </td>
      </tbody>
    </table>
  </div>

  <div class="span5">
    <ul class="nav nav-tabs nav-stacked">
      <li>
        <%= link_to files_spdx_doc_path(@spdx_doc) do %>
          <i class="icon-file-alt"></i>
          Files (<%= @package.files.count %>)
        <% end %>
      </li>
      <li>
        <%= link_to package_comments_path(@package) do %>
          <i class="icon-comment"></i>
          Comments (<%= @package.comments.count %>)
        <% end %>
      </li>
    </ul>
    <%= form_for [@package, @package_comment] do |f| %>
      <div class="input-append">
        <%= f.text_field :content, placeholder: "Comment on this package", class: "span10", disabled: true %>
        <%= f.submit "Add comment", class: "btn btn-primary", disabled: true %>
      </div>
    <% end %>
  </div>
</div>